smarthouse/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.WebsiteIndexView.as_view(), name='web_index'),
    url(r'^houses/(?P<pk>\d+)/details/$', views.HouseDetailView.as_view(), name='house_detail'),
    url(r'^dashboard/$', views.DashboardIndex.as_view(), name='dashboard_index'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', views.CreateAccountView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^forgot-password/$', views.ResetPasswordRequestView.as_view(), name='forgot_password'),
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.PasswordResetConfirmView.as_view(),
        name='reset_password_confirm'),
    url(r'^search/$', views.SearchView.as_view(), name='web_search'),

    url(r'^dashboard/posthouse/$', views.PostHouseView.as_view(), name='post_house'),
    url(r'^dashboard/myposts/$', views.MyHousePostsView.as_view(), name='myposts'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/delete/$', views.DeleteHouseView.as_view(), name='delete_house'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/update/$', views.UpdateHouseView.as_view(), name='update_house'),
    url(r'^dashboard/bookings/$', views.MyClientHouseBookingView.as_view(), name='my_house_booking'),
    url(r'^dashboard/payments/$', views.MyClientHousePaymentView.as_view(), name='payments'),
    url(r'^dashboard/myposts/search/$', views.SearchAdminView.as_view(), name='search_admin'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/update_gallery/$', views.UpdateGalleryView.as_view(), name='update_gallery'),
    url(r'^api/(?P<pk>\d+)/publish/$', views.PublishPost.as_view(), name='publish'),
    url(r'^checkout/(?P<pk>\d+)/$', views.Checkout.as_view(), name='checkout'),
    url(r'^contactus/$', views.ContactUsView.as_view(), name='contactus'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^api/mapdata/$', views.MapDataView.as_view(), name='map_data_endpoint'),
    url(r'^mapview/$', views.MapView.as_view(), name='map_view'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^mpesacallback/$', views.MpesaNotificationHandler.as_view(), name='callback'),
    url(r'^ussd/$', views.ussd_test, name='ussd'),
    url(r'^mapview/(?P<pk>\d+)/$', views.SingleMapView.as_view(), name='single_map'),



]

smartkeja/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'', include('smarthouse.urls', namespace='smarthouse'),),
                  url(r'^admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'SmartKeja'

smartkeja/templates/site/about.html
{% extends 'site/index.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="card">
            <div class="body">
                <div class="media-body">
                    <img src="{% static 'images/aboutimage.jpeg' %}" width="100%" height="350px">
                </div>
                Smart Keja is an online platform that gives access to the users who want to quickly find and get a house
                to rent or buy.
                The platform allow the agents and sole house owners to manage and upload houses they want to sell or
                rent easily
                by providing an intuitive dashboard for a collective actions.
                The platform offers connection between the clients and the house owners reducing time a customer
                would have spent to physically find a house to buy or rent.
                Financially this is the way to go. You dont have to spend allot of money to travel to different
                locations, making phone
                call for to different house providers in order to get a house. with this platform to find a house is
                just one click and you
                are done. the rest of money you would have spent you would spent to find a house.
            </div>
        </div>
        </div>
    </div>
{% endblock %}

smartkeja/templates/site/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Welcome To | SmartKeja</title>
    <!-- Favicon-->
    {#    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">#}
    {% include 'css.html' %}
    <style>
        li a:hover {
            background-color: white;
            color: green;
        }
    </style>

</head>
<body class="theme-blue">

<div class="overlay"></div>
<nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse"
               data-target="#navbar-collapse" aria-expanded="false"></a>

            <a class="navbar-brand" href="{% url 'smarthouse:web_index' %}">SmartKeja</a>
            {#            <div class="col-md-6">#}
            {#            <input type="text" placeholder="search here" class="form-control" >#}
            {#            </div>#}
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">

            <ul class="nav navbar-nav navbar-right">

                <li><a href="{% url 'smarthouse:web_index' %}"
                       style="color: white;font-weight: bold; font-family: Roboto">HOME</a></li>
                <li><a href="{% url 'smarthouse:about' %}" class="" style="color: white; font-weight: bold; font-family: Roboto">ABOUT US</a></li>
                <li><a href="{% url 'smarthouse:contactus' %}" class=""
                       style="color: white;font-weight: bold;font-family: Roboto">CONTACT US</a></li>

                <li class="dropdown pull-right">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                       role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons" style="font-size: 32px; margin-bottom: 20px">account_circle</i>
                    </a>
                    <ul class="dropdown-menu pull-right">

                        {% if request.user.is_authenticated %}
                            <li>
                                <a href=""><i class="material-icons" style="color: green;">person</i>
                                    <span><b>@ {{ request.user.username  | lower  }}</b></span>
                                </a>
                            </li>

                            {% if account_type == 'owner' or account_type == 'agent' %}

                                <li>
                                    <a href="{% url 'smarthouse:dashboard_index' %}"><i class="material-icons"
                                                                                   style="color: green">desktop_mac</i>Dashboard</a>
                                </li>
                            {% endif %}


                            <li>
                                <a href="{% url 'smarthouse:logout' %}"><i class="material-icons" style="color: green">power_settings_new</i>Logout</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'smarthouse:login' %}"><i class="material-icons" style="color: green">power_settings_new</i>Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</nav>
<!---endof navbar-->
<!-- Left Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar" style="width: 0 !important;">
        <!-- User Info -->

        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">

                <li class="active">
                </li>

            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        {#        <div class="legal">#}
        {#            <div class="copyright">#}
        {#                &copy; 2017 - 2018 <a href="javascript:void(0);">H-Board Leading Outdoor Software</a>.#}
        {#            </div>#}
        {#            <div class="version">#}
        {#                <b>Version: </b> 1.0 Beta#}
        {#            </div>#}
        {#        </div>#}
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
</section>
<!-- End left Bar -->


<div class="content">
    <div class="container-fluid">
        <div class="col-md-10 pull-right" style="margin-top: 140px;">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>

{% include 'js.html' %}
</body>
</html>

smartkeja/templates/site/checkout.html
{% extends 'site/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="row clearfix">
        <div class="header">
            <h4>Checkout Here or <a href="{% url 'smarthouse:web_index' %}">Go back</a></h4>
        </div>

        <div class="body">
            <div class="col-md-12">
                <img src="{% static 'images/mpesalogo1.png' %}" class="img img-responsive">
                <h6>How To Pay</h6>
                <span>The Process is easy as ABCD just follow the following steps</span>
                <hr/>
                <ul class="list-group">
                    <li class="list-group-item">
                        Step 1
                        <br/>
                        Enter you phone number in the form below

                    </li>

                    <li class="list-group-item">
                        Step 2
                        <br/>
                        Click on checkout and check you phone number for a confirmation.
                    </li>
                    <li class="list-group-item">
                        Step 3
                        <br>
                        Check your phone number and enter the M-pesa pin on the prompt to complete the transaction.
                        Done!!!
                    </li>
                </ul>
                <form action="#" method="post">

                    <div class="row">
                        <div class="col-md-6">
                            <label id="amount" for="amount">Amount</label>
                            <input type="text" class="form-control" id="amount"
                                   value="{% if house.on_sale %} {{ house.sale_price }}{% else %}{{ house.rent_price }}{% endif %}"
                                   disabled>
                            <input type="hidden" name="house_id" value="{{ house.id }}">
                            <label for="phoneNumber">Your Phone Number</label>
                            <input type="number" class="form-control" name="phone_number" id="phoneNumber"
                                   placeholder="07XX-XXXX-XXX" required>
                            <br/>
                            <input type="hidden" class="form-control" id="amount" name="amount"
                                   value="{% if house.on_sale %} {{ house.sale_price }}{% else %}{{ house.rent_price }}{% endif %}"
                            >
                            {% csrf_token %}
                            <input type="submit" class="btn btn-primary waves-effect" value="CHECKOUT"
                                   style="margin-bottom: 15px!important;">
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

smartkeja/templates/site/house_details.html
{% extends 'site/base.html' %}

{% block content %}
    <style>
        img {
            width: 400px !important;
            height: 250px !important;
        }
    </style>
    <div class="row clearfix">
        <div class="container-fluid">
            <div class="card">
                <div class="header">
                    <h2>
                        Book Now
                    </h2>
                </div>
                <div class="row">
                    <div class="container-fluid">

                        <div class="col-lg-12 col-md-12  col-sm-12 col-xs-12" style="margin: 10px;">
                            {% if messages %}
                                <ul class="list-group" style="list-style: none">
                                    {% for message in messages %}
                                        <li class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                                    aria-hidden="true">&times;</span></button>
                                            {{ message }} &nbsp;<a href="{% url 'smarthouse:web_index' %}"
                                                                   class="alert-link">Go back to homepage</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            <div class="col-md-6">
                                <div class="body">
                                    <h4 class="media-heading">Description</h4>

                                    <p style="font-family: Roboto; font-size: 16px;">A {{ house.bedrooms }} located
                                        at {{ house.location }}
                                        {% if house.on_sale %}Going for KSH {{ house.sale_price }}
                                        {% else %}
                                            With Rent fee of KSH {{ house.rent_price }} Per Month
                                        {% endif %}
                                        <br>
                                        This property is managed by {{ house.managed_by.get_full_name }}<br>
                                        For more information you can contact him via {{ house.managed_by.email }} or
                                        {{ phone_number }}
                                    </p>

                                    <a href="{% url 'smarthouse:checkout' pk=house.pk %}" class="btn btn-primary">Checkout</a>
                                </div>

                            </div>

                            <div class="col-md-6">
                                <div class="card">
                                    <div class="body">
                                        <div id="carousel-example-generic_2" class="carousel slide"
                                             data-ride="carousel">
                                            <!-- Indicators -->
                                            <ol class="carousel-indicators">
                                                <li data-target="#carousel-example-generic_2" data-slide-to="0"
                                                    class="active"></li>
                                                <li data-target="#carousel-example-generic_2" data-slide-to="1"></li>
                                                <li data-target="#carousel-example-generic_2" data-slide-to="2"></li>
                                                <li data-target="#carousel-example-generic_2" data-slide-to="3"></li>
                                                <li data-target="#carousel-example-generic_2" data-slide-to="4"></li>
                                                <li data-target="#carousel-example-generic_2" data-slide-to="5"></li>
                                            </ol>
                                            <!-- Wrapper for slides -->
                                            <div class="carousel-inner" role="listbox">
                                                <div class="item active">
                                                    <img src="{% if gallery.image1 %}{{ gallery.image1.url }}{% else %} {{ house.primary_img.url }} {% endif %}"/>
                                                    <div class="carousel-caption">
                                                        <h3>House First view</h3>
                                                    </div>
                                                </div>

                                                <div class="item">
                                                    <img src="


                                                            {% if gallery.image2 %}{{ gallery.image2.url }}{% else %} {{ house.primary_img.url }}  {% endif %}"/>
                                                    <div class="carousel-caption">
                                                        <h3>House's Second view</h3>
                                                    </div>
                                                </div>
                                                <div class="item">
                                                    <img src="


                                                            {% if gallery.image3 %}{{ gallery.image3.url }}{% else %} {{ house.primary_img.url }} {% endif %}"/>
                                                    <div class="carousel-caption">
                                                        <h3>House's Third view</h3>

                                                    </div>
                                                </div>

                                                <div class="item">
                                                    <img src="


                                                            {% if gallery.image4 %}{{ gallery.image4.url }}{% else %}{{ house.primary_img.url }}{% endif %}"/>
                                                    <div class="carousel-caption">
                                                        <h3>House's fourth view</h3>
                                                        <p>Located at {{ gallery.board.location }}</p>
                                                    </div>
                                                </div>

                                                <div class="item">
                                                    <img src="


                                                            {% if gallery.image5 %}{{ gallery.image5.url }}{% else %}{{ house.primary_img.url }} {% endif %}"/>
                                                    <div class="carousel-caption">
                                                        <h3>House's fifth view</h3>

                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <!-- Controls -->
                                        <a class="left carousel-control" href="#carousel-example-generic_2"
                                           role="button" data-slide="prev">
                                                <span class="glyphicon glyphicon-chevron-left"
                                                      aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        <a class="right carousel-control" href="#carousel-example-generic_2"
                                           role="button" data-slide="next">
                                                <span class="glyphicon glyphicon-chevron-right"
                                                      aria-hidden="true"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

smartkeja/templates/site/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Sign In | SmartKeja</title>
    <!-- Favicon-->
    <link rel="icon" href="{% static '' %}favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static 'plugins/node-waves/waves.css' %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static 'plugins/animate-css/animate.css' %}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body class="login-page">
    <div class="login-box">
        <div class="logo">
            <div class="logo">
         <a href="javascript:void(0);">S<b>martKeja</b></a>
        <small>Sign in Here</small>
    </div>
        </div>
        <div class="card">
            <div class="body">
                {% if error %}
                    <div class="alert alert-warning">
                    {{ error | capfirst }}
                    </div>
                {% endif %}

              {% if messages %}
                <ul class="list-group" style="list-style: none">
                    {% for message in messages %}
                        <li class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}

                <form id="sign_in" method="POST">
                    <div class="msg">Sign in to  SmartKeja</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="username" placeholder="Username" required autofocus>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password" placeholder="Password" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-8 p-t-5">
                            <input type="checkbox" name="rememberme" id="rememberme" class="filled-in chk-col-blue">
                            <label for="rememberme">Remember Me</label>
                        </div>
                        <div class="col-xs-4">
                            {% csrf_token %}
                            <button class="btn btn-block bg-light-blue waves-effect" type="submit">SIGN IN</button>
                        </div>
                    </div>
                    <div class="row m-t-15 m-b--20">
                        <div class="col-xs-6">
                            <a href="{% url 'smarthouse:signup' %}">Register Now!</a>
                        </div>
                        <div class="col-xs-6 align-right">
                            <a href="{% url 'smarthouse:forgot_password' %}">Forgot Password?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static 'plugins/node-waves/waves.js' %}"></script>

    <!-- Validation Plugin Js -->
    <script src="{% static 'plugins/jquery-validation/jquery.validate.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'js/admin.js' %}"></script>
    <script src="{% static 'js/pages/examples/sign-in.js' %}"></script>
</body>

</html>

smartkeja/templates/site/search_template.html
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="container-fluid">
        <form method="get" action="{% url 'smarthouse:search' %}">
            <div class="row">
                <div class="col-md-8">
                    <p>Search by location here</p>
                    <select class="form-control show-tick" data-live-search="true" id="locations" name="location">
                        <option value="any"> Any other part in kenya</option>
                        {% for house in house_options %}
                                <option value="{{ house.location }}">{{ house.location }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-4">
                    <div class="demo-switch">
                        <div class="switch">
                            <p>Include price range filter</p>
                            <label>NO<input type="checkbox" id="switch"><span class="lever"></span>YES</label>
                        </div>
                    </div>
                </div>
            </div>
            <section id="price-range">
            <div class="row">
                <div class="col-md-8">
                    <div id="range-slider">
                        <div class="irs-demo">
                            <input type="text" id="range" value=""/>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="low_price" id="low_price" value="" >
                <input type="hidden" name="high_price" id="high_price" value="" >
            </div>

            </section>

        <div class="row">
            <div class="col-md-8" style="margin-bottom: 15px!important;margin-top: 15px!important;">
                <button class="btn btn-primary  waves-effect pull-right">SEARCH</button>
            </div>
        </div>
        </form>
        </div>

    </div>
</div>

smartkeja/templates/site/single_map.html
{% extends 'site/base.html' %}

{% block content %}
    <style>
        img {
            width: 400px !important;
            height: 250px !important;
        }
    </style>
    <div class="row clearfix">
        <div class="container-fluid">
            <div class="card">
                <div class="header">
                    <h2>
                        MAP View
                    </h2>
                </div>
                <div class="row">
                    <div class="container-fluid">

                      <div class="body">

                          <div id="map" style="height: 650px; width: auto;">

                          </div>
                      </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
   <script>

      function initMap() {
        var myLatLng = {lat: {{ house.lat }}, lng: {{house.lng}}};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 13,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: '{{ house.location}}'
        });
      }
    </script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC85mWXDYoa_O8r2NYK3ffyNZR2y2xYPxM&libraries=places&callback=initMap"
                            async defer></script>
{% endblock %}