smarthouse/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.WebsiteIndexView.as_view(), name='web_index'),
    url(r'^houses/(?P<pk>\d+)/details/$', views.HouseDetailView.as_view(), name='house_detail'),
    url(r'^dashboard/$', views.DashboardIndex.as_view(), name='dashboard_index'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', views.CreateAccountView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^forgot-password/$', views.ResetPasswordRequestView.as_view(), name='forgot_password'),
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.PasswordResetConfirmView.as_view(),
        name='reset_password_confirm'),
    url(r'^search/$', views.SearchView.as_view(), name='web_search'),

    url(r'^dashboard/posthouse/$', views.PostHouseView.as_view(), name='post_house'),
    url(r'^dashboard/myposts/$', views.MyHousePostsView.as_view(), name='myposts'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/delete/$', views.DeleteHouseView.as_view(), name='delete_house'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/update/$', views.UpdateHouseView.as_view(), name='update_house'),
    url(r'^dashboard/bookings/$', views.MyClientHouseBookingView.as_view(), name='my_house_booking'),
    url(r'^dashboard/payments/$', views.MyClientHousePaymentView.as_view(), name='payments'),
    url(r'^dashboard/myposts/search/$', views.SearchAdminView.as_view(), name='search_admin'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/update_gallery/$', views.UpdateGalleryView.as_view(), name='update_gallery'),
    url(r'^api/(?P<pk>\d+)/publish/$', views.PublishPost.as_view(), name='publish'),
    url(r'^checkout/(?P<pk>\d+)/$', views.Checkout.as_view(), name='checkout'),
    url(r'^contactus/$', views.ContactUsView.as_view(), name='contactus'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^api/mapdata/$', views.MapDataView.as_view(), name='map_data_endpoint'),
    url(r'^mapview/$', views.MapView.as_view(), name='map_view'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^mpesacallback/$', views.MpesaNotificationHandler.as_view(), name='callback'),
    url(r'^ussd/$', views.ussd_test, name='ussd'),
    url(r'^mapview/(?P<pk>\d+)/$', views.SingleMapView.as_view(), name='single_map'),



]

smartkeja/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'', include('smarthouse.urls', namespace='smarthouse'),),
                  url(r'^admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'SmartKeja'

smartkeja/templates/dashboard/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>{% block title %}Welcome To | SmartKeja{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    {% include 'css.html' %}
</head>

<body class="theme-blue">
    <!-- Page Loader -->
{#    <div class="page-loader-wrapper">#}
{#        <div class="loader">#}
{#            <div class="preloader">#}
{#                <div class="spinner-layer pl-red">#}
{#                    <div class="circle-clipper left">#}
{#                        <div class="circle"></div>#}
{#                    </div>#}
{#                    <div class="circle-clipper right">#}
{#                        <div class="circle"></div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#            <p>Please wait...</p>#}
{#        </div>#}
{#    </div>#}
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <div class="search-bar">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="START TYPING...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="#">SmartKeja</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">

                    <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="{% static 'images/user.png' %}" width="48" height="48" alt="User" />
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></div>
                    <div class="email">{{ request.user }}</div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="{% url 'smarthouse:web_index' %}"><i class="material-icons">web</i>View Client Side</a></li>
                            <li role="seperator" class="divider"></li>
                            <li><a href="{% url 'smarthouse:logout' %}"><i class="material-icons">input</i>Sign Out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active">
                        <a href="{% url 'smarthouse:dashboard_index' %}">
                            <i class="material-icons">home</i>
                            <span>Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'smarthouse:myposts' %}">
                            <i class="material-icons">widgets</i>
                            <span>My Houses</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'smarthouse:post_house' %}">
                            <i class="material-icons">layers</i>
                            <span>Add House</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'smarthouse:payments' %}">
                            <i class="material-icons">account_balance</i>
                            <span>Payments</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'smarthouse:my_house_booking' %}">
                            <i class="material-icons">chrome_reader_mode</i>
                            <span>Bookings</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'smarthouse:map_view' %}">
                            <i class="material-icons">place</i>
                            <span>View On Map</span>
                        </a>
                    </li>

                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2017<a href="javascript:void(0);">SmartKeja</a>.
                </div>
                <div class="version">
                    <b>Version: </b> 1.0
                </div>
            </div>
            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->
    </section>

    <section class="content">
        <div class="container-fluid">

        {% block widgets %}
            <!-- Widgets -->
            <div class="row clearfix">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-pink hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">playlist_add_check</i>
                        </div>
                        <div class="content">
                            <div class="text">TOTAL HOUSES</div>
                            <div class="number count-to" data-from="0" data-to="" data-speed="15" data-fresh-interval="20">
                                {{ total_houses }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-cyan hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">chrome_reader_mode</i>
                        </div>
                        <div class="content">
                            <div class="text">BOOKED HOUSES</div>
                            <div class="number count-to" data-from="0" data-to="257" data-speed="1000" data-fresh-interval="20">{{ booked_houses }}</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-light-green hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">class</i>
                        </div>
                        <div class="content">
                            <div class="text">AVAILABLE</div>
                            <div class="number count-to" data-from="0" data-to="243" data-speed="1000" data-fresh-interval="20">{{ vacant_houses }}</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-orange hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">help</i>
                        </div>
                        <div class="content">
                            <div class="text">UN PUBLISHED </div>
                            <div class="number count-to" data-from="0" data-to="1225" data-speed="1000" data-fresh-interval="20">{{ unpublished_houses }}</div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Widgets -->
        {% endblock %}
            <!-- CPU Usage -->
            <div class="row clearfix">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    {% block content %}
                        <div class="card">
                        <div class="body">
                            <div id="map" style="width: 885px; height: 500px;">
                                <img src="{% static 'images/aboutimage.jpeg' %}" href="80%" width="100%">
                            </div>
                        </div>
                        </div>

                    {% endblock %}
                </div>
            </div>
            <!-- #END# CPU Usage -->
        </div>
    </section>
    {% include 'js.html' %}

<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5a8bf5d2d7591465c707d3b7/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

</body>

</html>