smarthouse/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.WebsiteIndexView.as_view(), name='web_index'),
    url(r'^houses/(?P<pk>\d+)/details/$', views.HouseDetailView.as_view(), name='house_detail'),
    url(r'^dashboard/$', views.DashboardIndex.as_view(), name='dashboard_index'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', views.CreateAccountView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^forgot-password/$', views.ResetPasswordRequestView.as_view(), name='forgot_password'),
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.PasswordResetConfirmView.as_view(),
        name='reset_password_confirm'),
    url(r'^search/$', views.SearchView.as_view(), name='web_search'),

    url(r'^dashboard/posthouse/$', views.PostHouseView.as_view(), name='post_house'),
    url(r'^dashboard/myposts/$', views.MyHousePostsView.as_view(), name='myposts'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/delete/$', views.DeleteHouseView.as_view(), name='delete_house'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/update/$', views.UpdateHouseView.as_view(), name='update_house'),
    url(r'^dashboard/bookings/$', views.MyClientHouseBookingView.as_view(), name='my_house_booking'),
    url(r'^dashboard/payments/$', views.MyClientHousePaymentView.as_view(), name='payments'),
    url(r'^dashboard/myposts/search/$', views.SearchAdminView.as_view(), name='search_admin'),
    url(r'^dashboard/myposts/(?P<pk>\d+)/update_gallery/$', views.UpdateGalleryView.as_view(), name='update_gallery'),
    url(r'^api/(?P<pk>\d+)/publish/$', views.PublishPost.as_view(), name='publish'),
    url(r'^checkout/(?P<pk>\d+)/$', views.Checkout.as_view(), name='checkout'),
    url(r'^contactus/$', views.ContactUsView.as_view(), name='contactus'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^api/mapdata/$', views.MapDataView.as_view(), name='map_data_endpoint'),
    url(r'^mapview/$', views.MapView.as_view(), name='map_view'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^mpesacallback/$', views.MpesaNotificationHandler.as_view(), name='callback'),
    url(r'^ussd/$', views.ussd_test, name='ussd'),
    url(r'^mapview/(?P<pk>\d+)/$', views.SingleMapView.as_view(), name='single_map'),



]

smartkeja/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'', include('smarthouse.urls', namespace='smarthouse'),),
                  url(r'^admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'SmartKeja'

smarthouse/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse

from smarthouse.AfricasTalkingGateway import AfricasTalkingGateway, AfricasTalkingGatewayException
# Create your models here.
from smarthouse.signals import checkout_completed, checkout_failed


class Agent(models.Model):
    user = models.OneToOneField(User)
    agency_name = models.CharField(max_length=100, )
    phone_number = models.CharField(max_length=13, )

    def __str__(self):
        return self.agency_name


class HouseOwner(models.Model):
    user = models.OneToOneField(User)
    phone_number = models.CharField(max_length=13, )


class House(models.Model):
    managed_by = models.ForeignKey(User)
    lat = models.FloatField()
    lng = models.FloatField()
    location = models.CharField(max_length=200)
    rent_price = models.FloatField()
    sale_price = models.FloatField()
    bedrooms = models.IntegerField()
    description = models.TextField()
    on_sale = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    primary_img = models.ImageField(upload_to='uploads/')
    is_published = models.BooleanField(default=False)
    date_posted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-is_available', '-date_posted')

    def get_absolute_url(self):
        return reverse('smarthouse:house_detail', args=[self.pk])

    def __str__(self):
        return "A {}-bedroom(s) House at {}".format(self.bedrooms, self.location)


class HouseGallery(models.Model):
    house = models.ForeignKey(House)
    image1 = models.ImageField(upload_to='uploads/', null=True, blank=True)
    image2 = models.ImageField(upload_to='uploads/', null=True, blank=True)
    image3 = models.ImageField(upload_to='uploads/', null=True, blank=True)
    image4 = models.ImageField(upload_to='uploads/', null=True, blank=True)
    image5 = models.ImageField(upload_to='uploads/', null=True, blank=True)

    def __str__(self):
        return "Gallery for {}".format(str(self.house))


class Booking(models.Model):
    house = models.ForeignKey(House)
    booked_by = models.CharField(max_length=20, null=True, default='')
    date_booked = models.DateTimeField(auto_now_add=True)
    cleared = models.BooleanField(default=False)
    deposit_amount = models.FloatField()

    def __str__(self):
        return "Booking for {}".format(str(self.house))


class Payment(models.Model):
    txn_id = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=13)
    amount = models.FloatField()
    house = models.ForeignKey(House)
    status = models.CharField(max_length=32)
    PAYMENT_TYPE_CHOICE = [
        ('Rent', 'Rent'),
        ('Purchase', 'Purchase')
    ]
    payment_type = models.CharField(max_length=20, choices=PAYMENT_TYPE_CHOICE, default=PAYMENT_TYPE_CHOICE[0][0])
    date_paid = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_paid',)

    def __str__(self):
        return "{} for {}".format(self.payment_type, str(self.house))


class ContactUs(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField(max_length=200)

    def __str__(self):
        return "Contact message from {}".format(self.email)


def complete_txn(sender, **kwargs):
    payment, created = get_object_or_404(Payment, txn_id=kwargs['txn_id'])
    payment.status = kwargs['status']
    if created and kwargs['status'].lower() == 'success':
        # send sms
        gateway = AfricasTalkingGateway(settings.USERNAME, settings.API_KEY)
        try:
            message = kwargs['message']
            gateway.sendMessage(kwargs['phone_number'], message)

        except AfricasTalkingGatewayException, e:
            print "error sending sms %s" % e

    payment.save()


checkout_completed.connect(complete_txn)
checkout_failed.connect(complete_txn)

smartkeja/templates/dashboard/pages/myhouses.html
{% extends 'dashboard/index.html' %}
{% load staticfiles %}
{% block widgets %}

{% endblock %}

{% block content %}
     {% if messages %}
            <ul class="list-group" style="list-style: none">
                {% for message in messages %}
                    <li class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% if house_posts %}
        {% for house in house_posts %}
            <div class="row clearfix">
            <div class="card">
                <div class="header">
                    <h2>
                        <a href="{{ board.get_absolute_url }}" style="color: #4CAF50">
                            House Located At <i class="material-icons">room</i> {{ house.location }}
                        </a>
                        <small></small>
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{% url 'smarthouse:update_house' pk=house.pk %}"><i class="material-icons"
                                                   style="color: #3F51B5">create</i>Edit
                                    Info</a></li>
                                <li><a href="{% url 'smarthouse:update_gallery' pk=house.pk %}"><i
                                        class="material-icons"
                                        style="color: #CDDC39;">add_a_photo</i>
                                    Add Images</a></li>
                                <li><a href="{% url 'smarthouse:delete_house' pk=house.pk %}"><i class="material-icons"
                                                   style="color: #F44336">delete</i>Remove
                                </a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">

                    <div class="media">
                        <div class="media-left">
                            <a href="javascript:void(0);">
                                <img class="media-object thumbnail" src="{{ house.primary_img.url }}"
                                     width="280" height="150">
                            </a>
                        </div>
                        <div class="media-body">
                            <div class="row">
                                <div class="col-md-7">
                                    <h4 class="media-heading">Description</h4>

                                    <p style="font-family: Roboto; font-size: 16px;">A {{ house.bedrooms }} located
                                        at {{ house.location }}
                                        {% if house.on_sale %}Going for KSH {{ house.sale_price }}
                                        {% else %}
                                            With Rent fee of KSH {{ house.rent_price }} Per Month
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="col-md-5">
                                    <style>
                                        li {
                                            margin-top: 5px;
                                        }
                                    </style>
                                    <ul style="list-style: none">
                                        {% if house.on_sale %}
                                            <li>
                                                <a href="#" class="btn btn-primary waves-effect">BUY NOW</a>
                                            </li>
                                        {% else %}
                                            <li>
                                                <a href="#" class="btn btn-success waves-effect">BOOK NOW</a>
                                            </li>

                                        {% endif %}

                                        {% if house.is_published %}

                                            <li>
                                                <button class="btn btn-default waves-effect"
                                                        onclick="showConfirmMessage('{{ house.pk }}', 'off')">Un publish
                                                </button>
                                            </li>

                                        {% else %}
                                            <li>
                                                <button class="btn btn-default waves-effect"
                                                        onclick="showConfirmMessage('{{ house.pk }}', 'on')">PUBLISH
                                                </button>
                                            </li>

                                        {% endif %}

                                        <li>
                                            <a href="{% url 'smarthouse:delete_house' pk=house.pk %} "
                                               class="btn btn-danger">DELETE</a>
                                        </li>


                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="panel-footer">
                    <p>
                        <small style="font-size: 16px;">Status <span
                                style="color: teal;">
                                           {% if not house.is_available %} Not Available{% else %}
                                               Available {% endif %}
                                        </span>
                        </small>
                    </p>
                </div>

            </div>
            </div>
        {% endfor %}

        <div class="container-fluid pull-right">
            <nav>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <i class="material-icons">chevron_left</i>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="javascript:void(0);">
                                <i class="material-icons">chevron_left</i>
                            </a>
                        </li>
                    {% endif %}

                    {% for l in  page_obj.paginator.page_range %}
                        {% if forloop.counter <= 10 %}
                            <li class="{% if forloop.counter == page_obj.number %}active{% endif %}"><a
                                    href="?page={{ forloop.counter }}" class="waves-effect">{{ forloop.counter }}</a>
                            </li>
                        {% endif %}

                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}" class="waves-effect">
                                <i class="material-icons">chevron_right</i>
                            </a>

                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="javascript:void(0);">
                                <i class="material-icons">chevron_right</i>
                            </a>
                        </li>
                    {% endif %}


                </ul>
            </nav>
        </div>

    {% else %}
        <div class="alert alert-info">
            <p>You do not have any houses posted for sale or rent. <a href="{% url 'smarthouse:post_house' %}">Click
                here to post</a></p>
        </div>
    {% endif %}


    <!-- Jquery Core Js -->
    <script src="{% static 'js/hosts.js' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- SweetAlert Plugin Js -->
    <script src="{% static 'plugins/sweetalert/sweetalert.min.js' %}"></script>


    <script>
        var baseUrl = getBaseHostUrl();

        function showConfirmMessage(pk, option) {
            var text;
            if (option === 'on') {
                text = "You want to publish this post.";
            } else {
                text = "You Want to UnPublish this post!";
            }

            swal({
                title: "Are you sure?",
                text: text,
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#4CAF50",
                confirmButtonText: "Yes, Submit!",
                closeOnConfirm: false
            }, function () {
                var url = baseUrl + '/app/api/' + pk + '/publish/';

                $.ajax({
                    type: 'POST',
                    url: url,
                    dataType: 'json',
                    contentType: 'application/json',
                    data: JSON.stringify({publish_value: option}),
                    traditional: true,
                    success: function (response) {
                        console.log(response);
                        if (response['status_code'] === 200) {

                            swal("Completed!", response['message'], "success");
                            setTimeout(function () {
                                window.location.href = '/app/dashboard/myposts/'
                            }, 1500)
                        } else {
                            console.log("error ")
                        }
                    }
                });

            });
        }

    </script>
{% endblock %}

smartkeja/templates/dashboard/pages/post_house.html
{% extends 'dashboard/index.html' %}
{% load  staticfiles %}
{% block widgets %}
{% endblock %}
{% block content %}
    <style>
        /* Always set the map height explicitly to define the size of the div
         * element that contains the map. */
        #map {
            height: 100%;
        }

        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        #description {
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
        }

        #infowindow-content .title {
            font-weight: bold;
        }

        #infowindow-content {
            display: none;
        }

        #map #infowindow-content {
            display: inline;
        }

        .pac-card {
            margin: 10px 10px 0 0;
            border-radius: 2px 0 0 2px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
            outline: none;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
            background-color: #fff;
            font-family: Roboto;
        }

        #pac-container {
            padding-bottom: 12px;
            margin-right: 12px;
        }

        .pac-controls {
            display: inline-block;
            padding: 5px 11px;
        }

        .pac-controls label {
            font-family: Roboto;
            font-size: 13px;
            font-weight: 300;
        }

        #pac-input {
            background-color: #fff;
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
            margin-left: 12px;
            padding: 0 11px 0 13px;
            text-overflow: ellipsis;
            width: 400px;
        }

        #pac-input:focus {
            border-color: #4d90fe;
        }

        #title {
            color: #fff;
            background-color: #4d90fe;
            font-size: 25px;
            font-weight: 500;
            padding: 6px 12px;
        }

        #target {
            width: 345px;
        }

        {% comment %}
        start for text area css
        {% endcomment %}

        .textarea-container {
            position: relative;
            width: 50%;
        }

        textarea, .textarea-size {
            min-height: 25px;
            font-family: sans-serif;
            font-size: 14px;
            box-sizing: border-box;
            padding: 4px;
            border: 1px solid;
            overflow: hidden;
            width: 100%;
        }

        textarea {
            height: 100%;
            position: absolute;
            resize: none;
            white-space: normal;
        }

        .textarea-size {
            visibility: hidden;
            white-space: pre-wrap;
            word-wrap: break-word;
            overflow-wrap: break-word;
        }

        {% comment %} end of text area css {% endcomment %}

        .lbl-input {
            padding-left: 5px;
            color: #000;
        }

        .custom-input {
            height: 45px;

        }

    </style>
    <div class="row clearfix">
        <div class="card">
            <div class="header">
                <h2>
                    Post House by by filling the form below
                </h2>
            </div>
            <div class="container-fluid card body" style="background: #f0f0f0;">
                <div class="col-md-4 body">
                    You have Selected : <span style="color: green;font-weight: bold;" id="location_text"></span>
                    <form method="post" name="create_house_post_form" action="#" style="margin-top: 10px;"
                          onsubmit="return checkLocationSelected()" enctype="multipart/form-data">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="number" id="id_length" name="bedrooms" class="form-control custom-input"
                                       required>
                                <label class="form-label lbl-input">Number of Bedrooms</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <select class="form-control custom-input" id="posting_for" name="posting_for">
                                <option value="">Select Posting Option</option>
                                <option value="rent">For Renting</option>
                                <option value="sale">For Sale</option>
                            </select>
                        </div>
                        <div id="rent_price">

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" id="id_rent_price" name="id_rent_price"
                                           class="form-control custom-input">
                                    <label class="form-label lbl-input">Rent Price</label>
                                </div>
                            </div>
                        </div>
                        <div id="sale_price">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="number" id="id_sale_price" name="id_sale_price"
                                           class="form-control custom-input">
                                    <label class="form-label lbl-input">Sale Price</label>
                                </div>
                            </div>
                        </div>


                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="file" id="id_photo" name="primary_img" class="form-control"
                                       accept="image/*"
                                       value="Upload photo" required>
                            </div>
                        </div>
                        <div>
                            <input type="hidden" name="location" id="location">
                            <input type="hidden" name="lat" id="lat">
                            <input type="hidden" name="lng" id="lng">

                        </div>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Post House</button>
                    </form>
                </div>

                <div class="col-md-8">
                    <input id="pac-input" class="controls" type="text" placeholder="Search your location here"
                           style="margin-top: 10px;">
                    <div id="map" style="height: 520px; width:auto ;"></div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <script>
        $(document).ready(function (e) {
            e.preventDefault;
            $('#sale_price').hide();
            $('#rent_price').hide();

            $('#posting_for').on('change', function () {
                var selected_val = $(this).val();
                showPricesDiv(selected_val);
            });

        });

        function showPricesDiv(value) {
            if (value === 'rent') {
                document.getElementById('id_rent_price').setAttribute('required', '');
                document.getElementById('id_sale_price').removeAttribute('required');
                $('#sale_price').hide();
                $('#rent_price').show();
            }
            if (value === 'sale') {
                document.getElementById('id_sale_price').setAttribute('required', '');
                document.getElementById('id_rent_price').removeAttribute('required');
                $('#sale_price').show();
                $('#rent_price').hide();
            }
            if (value !== 'rent' && value !== 'sale') {
                $('#sale_price').hide();
                $('#rent_price').hide();
            }
        }


        function checkLocationSelected() {
            var location = document.forms["create_house_post_form"]["location"].value;

            if (location === '') {
                swal("Select a  location to continue!");
                return false
            } else {
                return true;
            }
        }
    </script>


{#    changed file#}

    <script>


      var marker=false;
      var map;
      function initAutocomplete() {
         map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -1.2885962273241198, lng: 36.823039054870605},
          zoom: 13,
          mapTypeId: 'roadmap'
         // mapTypeId: 'hybrid'
        });



     if (navigator.geolocation) {
         navigator.geolocation.getCurrentPosition(function (position) {
             initialLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude)
         });
     }


        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length === 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            if (!place.geometry) {
              console.log("Returned place contains no geometry");
              return;
            }
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });

        //my custom
    var geocoder = new google.maps.Geocoder();
          google.maps.event.addListener(map, 'click', function(event) {
    geocoder.geocode({
    'latLng': event.latLng
  }, function(results, status) {
    if (status === google.maps.GeocoderStatus.OK) {
      if (results[0]) {
        document.getElementById('location').value = results[0].formatted_address;
        document.getElementById('location_text').textContent = results[0].formatted_address;
        console.log(results[0].geometry.location.lat());
        console.log(results[0].geometry.location.lng());

         document.getElementById('lat').value = results[0].geometry.location.lat(); //latitude
         document.getElementById('lng').value = results[0].geometry.location.lng(); //longitude

      }
    }
  });
});
          //end of my custom


        var marker = false;

        //Listen for any clicks on the map.
       google.maps.event.addListener(map, 'click', function(event) {
        //Get the location that the user clicked.
        var clickedLocation = event.latLng;
        //If the marker hasn't been added.
        if(marker === false){
            //Create the marker.
            marker = new google.maps.Marker({
                position: clickedLocation,
                map: map,
                draggable: true //make it draggable
            });
            //Listen for drag events!
            google.maps.event.addListener(marker, 'dragend', function(event){

                 var currentLocation = marker.getPosition();
    //Add lat and lng values to a field that we can save.
         // document.getElementById('lat').value = currentLocation.lat(); //latitude
         // document.getElementById('lng').value = currentLocation.lng(); //longitude
            });
        } else{
            //Marker has already been added, so just change its location.
            marker.setPosition(clickedLocation);
        }
        //Get the marker's location.
        //markerLocation();

         var currentLocation = marker.getPosition();
        //Add lat and lng values to a field that we can save.
        document.getElementById('lat').value = currentLocation.lat(); //latitude
        document.getElementById('lng').value = currentLocation.lng(); //longitude

           //console.log("lat "+currentLocation.lat());
           //console.log("lng  "+currentLocation.lng());
    });


}



    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC85mWXDYoa_O8r2NYK3ffyNZR2y2xYPxM&libraries=places&callback=initAutocomplete"
         async defer></script>







































{% endblock %}